* NumPy is an open source python library used for working with arrays, linear algebra, fourier transform and matrices

* for the fast computation most of python library are written in c and c++ 

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
print('max element:',np.max(arr))
print('min element:', np.min(arr))
print('mean of array:', np.mean(arr))
print('median of array:', np.median(arr))
print('point to point of array:', np.ptp(arr))
print('variable of array:', np.var(arr))
print('standard deviation of array:', np.min(arr))
print('square root:', np.sqrt(arr))
print('min element:', np.min(arr))

max element: 5
min element: 1
mean of array: 3.0
median of array: 3.0
point to point of array: 4
variable of array: 2.0
standard deviation of array: 1
square root: [1.         1.41421356 1.73205081 2.         2.23606798]


In [194]:
#multiplying array
s=np.array([1,2,3])
t=np.array([4,5,6])
s*t

array([ 4, 10, 18])

In [196]:
from numpy import array
u=array([2.5,3.5,4.5])
v=array([1,2,3])
u*v

array([ 2.5,  7. , 13.5])

In [201]:
from numpy import array
w=array([45,2,1])
x=2
w*x


array([90,  4,  2])

In [206]:
#sorting array

#sort along first axis
y=np.array([[121,1],[45,9]])

print('along first axis:\n',np.sort(y,axis=0))

#sort along last axis
z=np.array([[44,5],[59,23]])

print('along last axis:\n',np.sort(z,axis=-1))

#along none
z=np.array([[1,24],[67,8]])
print('along none axis:\n', np.sort(z,axis=None))


along first axis:
 [[ 45   1]
 [121   9]]
along last axis:
 [[ 5 44]
 [23 59]]
along none axis:
 [ 1  8 24 67]


In [30]:
import numpy as np
a=np.array([[2,3,4,5],[56,67,78,89]])
a

array([[ 2,  3,  4,  5],
       [56, 67, 78, 89]])

In [81]:
print('order of matrix is:',a.shape)
print('dimension of array:',a.ndim)
print(type(a))
print('sum:',np.sum(a) )

order of matrix is: (2, 4)
dimension of array: 2
<class 'numpy.ndarray'>
sum: 304


In [42]:
print(a.data)

In [80]:
b=np.array([[20,21,22],[23,24,25],[26,27,28]])
print(b,'\n')
print('data type of array: ',b.dtype)
print('size of array:',b.size)
print('dimension of array:',b.ndim)
print('shape of array:',b.shape)
print('number of byte of each item is:',b.itemsize)
print('sum:',np.sum(b) )

[[20 21 22]
 [23 24 25]
 [26 27 28]] 

data type of array:  int32
size of array: 9
dimension of array: 2
shape of array: (3, 3)
number of byte of each item is: 4
sum: 216


In [79]:
c=np.array([['h'],['i'],['m'],['a'],['n'],['i']])
print(c)
print()
print('number of byte of each item',c.itemsize)
print('shape of array',c.shape)


[['h']
 ['i']
 ['m']
 ['a']
 ['n']
 ['i']]

number of byte of each item 4
shape of array (6, 1)


In [77]:
d=np.array([[2.3,3.5,3.4],[2.3,2.3,5.6],[8.7,7.8,78.8]])
print(d)
print()
print('number of bytes of each element:',d.itemsize)
print('shape of array',d.shape)
print('sum:',np.sum(d) )

[[ 2.3  3.5  3.4]
 [ 2.3  2.3  5.6]
 [ 8.7  7.8 78.8]]

number of bytes of each element: 8
shape of array (3, 3)
sum: 114.69999999999999


In [76]:
e=np.array([[80,345,46],[12,34,56],[67,87,45]],dtype=np.complex64)
print(e)
print()
print('size of array:',e.size)
print('byte of each item:',e.itemsize)
print('data type:',e.dtype)
print('shape of array:',e.shape)
print('dimension of array:',e.ndim)
print('sum:',np.sum(f) )

[[ 80.+0.j 345.+0.j  46.+0.j]
 [ 12.+0.j  34.+0.j  56.+0.j]
 [ 67.+0.j  87.+0.j  45.+0.j]]

size of array: 9
byte of each item: 8
data type: complex64
shape of array: (3, 3)
dimension of array: 2
sum: (772+0j)


In [75]:
f=np.array([[80,345,46],[12,34,56],[67,87,45]],dtype=np.complex128)
print(f)
print()
print('size of array:',f.size)
print('byte of each item:',f.itemsize)
print('data type:',f.dtype)
print('shape of array:',f.shape)
print('dimension of array:',f.ndim)
print('sum:',np.sum(f) )

[[ 80.+0.j 345.+0.j  46.+0.j]
 [ 12.+0.j  34.+0.j  56.+0.j]
 [ 67.+0.j  87.+0.j  45.+0.j]]

size of array: 9
byte of each item: 16
data type: complex128
shape of array: (3, 3)
dimension of array: 2
sum: (772+0j)


In [94]:
g=np.array([[12,23,45],[45,56,88],[67,89,9]],dtype=np.float64)
print(g)

[[12. 23. 45.]
 [45. 56. 88.]
 [67. 89.  9.]]


In [95]:
#min value
print('min value',np.min(g))
print('min value in a col',np.min(g,axis=0))
print('min value in a row',np.min(g,axis=1))
#max value
print()
print('max value',np.max(g))
print('max value in a col',np.max(g,axis=0))
print('max value in a row',np.max(g,axis=1))

#mean of array
print()
print('mean of array',np.mean(g))
print('mean of each col of array',np.mean(g,axis=0))
print('mean of each row of array',np.mean(g,axis=1))

#sum
print()
print('sum:',np.sum(g))
print('sum of each col',np.sum(g,axis=0))  #col
print('sum of each row',np.sum(g,axis=1)) #rows

min value 9.0
min value in a col [12. 23.  9.]
min value in a row [12. 45.  9.]

max value 89.0
max value in a col [67. 89. 88.]
max value in a row [45. 88. 89.]

mean of array 48.22222222222222
mean of each col of array [41.33333333 56.         47.33333333]
mean of each row of array [26.66666667 63.         55.        ]

sum: 434.0
sum of each col [124. 168. 142.]
sum of each row [ 80. 189. 165.]


In [98]:
#average
print('average',np.average(g))
print('average of each col',np.average(g,axis=0))
print('average of each row',np.average(g,axis=1))

#standard deviation
print()
print('standard deviation:',np.std(g))
print('standard deviation of each col',np.std(g,axis=0))
print('standard deviation of each rows',np.std(g,axis=1))

#variance 
print()
print('variance',np.var(g))
print('variance of each col',np.var(g,axis=0))
print('variance of each row',np.var(g,axis=1))

average 48.22222222222222
average of each col [41.33333333 56.         47.33333333]
average of each row [26.66666667 63.         55.        ]

standard deviation: 28.216534860010235
standard deviation of each col [22.60285134 26.94438717 32.29379025]
standard deviation of each rows [13.71941042 18.23915203 33.74413529]

variance 796.1728395061729
variance of each col [ 510.88888889  726.         1042.88888889]
variance of each row [ 188.22222222  332.66666667 1138.66666667]


In [156]:
h=np.array([2,3,4,6,7,8,0,8,5,44])
print('h=',h)
print()
i=np.array([12,23,34,45,56,67,78,89,90,34])
print('i=',i)
print()
print(np.average(h,weights=i))
print()
print('mean of h',np.mean(h))
print('mean of i',np.mean(i))
print('dimension of h:',h.ndim)
print('sorted array h-',np.sort(h))
print('sorted array i-',np.sort(i))

h= [ 2  3  4  6  7  8  0  8  5 44]

i= [12 23 34 45 56 67 78 89 90 34]

7.736742424242424

mean of h 8.7
mean of i 52.8
dimension of h: 1
sorted array h- [ 0  2  3  4  5  6  7  8  8 44]
sorted array i- [12 23 34 34 45 56 67 78 89 90]


In [117]:
j=np.array([[2,3,4],[6,7,8]])
print(j)
print('mean of i:',np.mean(j))

#percentile
print()
print('percentile:',np.percentile(j,100))
print('percentile of each col:',np.percentile(j,100,0))
print('percentile of each row:',np.percentile(j,100,1))
print()

#peek to peek
print('peek to peek col:',np.ptp(j,0))  #here max value-min value =ptp
print('peek to peek row:',np.ptp(j,1))

[[2 3 4]
 [6 7 8]]
mean of i: 5.0

percentile: 8.0
percentile of each col: [6. 7. 8.]
percentile of each row: [4. 8.]

peek to peek: [4 4 4]
peek to peek: [2 2]


* interquatile
* first quartile(Q1) is equal to the median of the n smallest entries
* third quartile(Q3) is equal to the median of the n largest entries
* second quartile(Q2) is the same as the ordinary median
* range is difference between the largest value and the smallest value in data set
* interquatile range is the difference between the Q3 and Q1 (it cover the center of the distribution and contain 50% of the observations)
  

In [192]:
import numpy as np
data=[23,34,45,67,78,990,7,45,56,34,56,76]

#first quartile 
Q1=np.median(data[:10])

#third quartile
Q3=np.median(data[10:])

#interquatile
IQR=Q3-Q1

print(IQR)

21.0


In [193]:
#interquatile range using numpy.percentile
import numpy as np
data=[12,23,4,56,67,78,45,34,23,34,45,56,67,67,45,3,4,7,8,6]

Q1=np.percentile(data,25,interpolation='midpoint')
Q3=np.percentile(data,75, interpolation='midpoint')
IQR=Q3-Q1

print(IQR)

48.5


In [122]:
k=np.array([[1,2,3,4],[5,6,7,8]])
print(k)
print()
print('order of array',k.shape)
print()
print('reshaping the array:\n',k.reshape(4,2))


[[1 2 3 4]
 [5 6 7 8]]

order of array (2, 4)

reshaping the array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [124]:
#slicing
l= np.array([[1,10,100,1000],[2,20,200,2000],[3,30,300,3000]])
print(l)

[[   1   10  100 1000]
 [   2   20  200 2000]
 [   3   30  300 3000]]


In [125]:
l[0,2] #[row,col]

100

In [128]:
l[2,3]

3000

In [129]:
l[-1]

array([   3,   30,  300, 3000])

In [130]:
l[-2]

array([   2,   20,  200, 2000])

In [131]:
l[0]

array([   1,   10,  100, 1000])

In [132]:
l[-3]

array([   1,   10,  100, 1000])

In [133]:
l[-1,0:2]

array([ 3, 30])

In [134]:
l[0:2,-1] 

array([1000, 2000])

In [135]:
#stacking

m=np.array([[1,2,3],[4,5,6],[7,8,9]])
n=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(m,'\n\n',n)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [140]:
print(np.stack((n,m)))


[[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]


In [165]:
#random number generator using numpy
from numpy import random
o=random.rand(2)            #for float numbers
#o=random.randint(50)       #for int numbers

print(o)

[0.93428975 0.48619002]


In [174]:
#generate random array
from numpy import random
#p=random.randint(50, size=(6))      # 1-D aray
p=random.randint(100,size=(3,5))    # 2-D array
print(p)

[[75  1 74 94 18]
 [14 39 44 36 53]
 [64 75 20 53 25]]


In [176]:
#creating scalars in numpy
import numpy as edunet
arr=edunet.array([3]) # size 1 array
print('input array:',arr)
print()

print('output scalar from input array:',edunet.asscalar(arr))

input array: [3]

output scalar from input array: 3


<ipython-input-176-121217d2e8a9>:6: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out=edunet.asscalar(arr)


In [181]:
import numpy as np
list1=[1,2,3]                #creating vector as row
list2=[[10],[20],[30]]       #creating vector as column

print('horizontal vector \n',np.array(list1))
print('\n vertical vector \n',np.array(list2))


horizontal vector 
 [1 2 3]

 vertical vector 
 [[10]
 [20]
 [30]]


In [187]:
#creating matrix using numpy.matrix class

import numpy as np

#string input
q=np.matrix('1 2 3; 4,5,0')
print('via string input: \n',q,'\n')

#array like input
r=np.matrix([[5,6,7],[7,7,8]])
print('via array like input:\n',r)

via string input: 
 [[1 2 3]
 [4 5 0]] 

via array like input:
 [[5 6 7]
 [7 7 8]]


In [189]:
#matrix maltiplication

import numpy as np
mat1=([-1,4],[2,3])
mat2=([9,-3],[6,1])

print('dot product of matrix: \n',np.dot(mat1,mat2))

dot product of matrix: 
 [[15  7]
 [36 -3]]
